name: Forums rotations reminder
on:
    push:
        branches:
            - master
    schedule:
        # Crontab assumes UTC
        # UTC-5 is Eastern time, I'm aiming for 9am eastern/2pm UTC.
        # Job should run every Monday at 2pm UTC
        - cron: "0 14 * * 1"

jobs:
    slack-notify:
        name: Slack notification
        runs-on: ubuntu-latest
        env:
            SLACK_API_TOKEN = ${{ secrets.SLACK_API_TOKEN }}
        steps:
            - uses: actions/checkout@v1

            - uses: actions/setup-python@v1
              with:
                  python-version: 3.7

            - name: Install python dependencies
              run: pip install -r ./forums-rotation/requirements.txt

            # Might as well run this every time, both on push and schedule
            - name: Test that everything imports
              run: python ./forums-rotation/whos-on-rotation.py --dry-run

            - name: Send notification
              if: github.event_name == 'schedule'
              run: python ./forums-rotation/whos-on-rotation.py
